import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { PolicyAnalysisResult } from "./policy-analyzer";

/**
 * Generates a professional PDF report from the Policy Analysis result.
 */
export async function generatePolicyAnalysisPDF(analysis: PolicyAnalysisResult, organizationName: string) {
    const doc = new jsPDF() as any;
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    doc.setFillColor(30, 41, 59); // si-navy
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Cyber Policy Analysis", 15, 25);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Organization: ${organizationName}`, 15, 33);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 15, 33, { align: "right" });

    // --- Executive Summary ---
    let yPos = 55;
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", 15, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const summaryLines = doc.splitTextToSize(analysis.executiveSummary, pageWidth - 30);
    doc.text(summaryLines, 15, yPos);
    yPos += (summaryLines.length * 5) + 15;

    // --- Identified Controls ---
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Identified Security Controls", 15, yPos);
    yPos += 5;

    const controlsData = analysis.identifiedControls.map(c => [
        c.name,
        c.status,
        c.details || "N/A"
    ]);

    doc.autoTable({
        startY: yPos,
        head: [['Control Name', 'Status', 'Details']],
        body: controlsData,
        headStyles: { fillColor: [59, 130, 246] }, // si-blue-primary
        alternateRowStyles: { fillColor: [248, 250, 252] },
        styles: { fontSize: 9 }
    });
    yPos = doc.lastAutoTable.finalY + 15;

    // --- Compliance Alignment ---
    if (yPos > doc.internal.pageSize.height - 60) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Compliance Alignment", 15, yPos);
    yPos += 5;

    const complianceData = analysis.complianceAlignment.map(c => [
        c.standard,
        `${c.alignmentScore}%`,
        c.notes || "N/A"
    ]);

    doc.autoTable({
        startY: yPos,
        head: [['Standard', 'Alignment', 'Notes']],
        body: complianceData,
        headStyles: { fillColor: [59, 130, 246] },
        styles: { fontSize: 9 }
    });
    yPos = doc.lastAutoTable.finalY + 15;

    // --- Maturity Gaps ---
    if (yPos > doc.internal.pageSize.height - 60) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Key Maturity Gaps", 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    analysis.maturityGaps.forEach((gap, index) => {
        const gapLines = doc.splitTextToSize(`${index + 1}. ${gap}`, pageWidth - 30);
        doc.text(gapLines, 15, yPos);
        yPos += (gapLines.length * 5) + 2;
    });
    yPos += 10;

    // --- Recommendations ---
    if (yPos > doc.internal.pageSize.height - 60) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Strategic Recommendations", 15, yPos);
    yPos += 5;

    const recsData = analysis.recommendations.map(r => [
        r.action,
        r.priority,
        r.impact
    ]);

    doc.autoTable({
        startY: yPos,
        head: [['Recommended Action', 'Priority', 'Impact']],
        body: recsData,
        headStyles: { fillColor: [244, 63, 94] }, // si-red
        styles: { fontSize: 9 }
    });

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: "center" });
        doc.text("Generated by CYRUS.PRO - Strategic Cyber Risk Intelligence", 15, doc.internal.pageSize.height - 10);
    }

    return doc;
}
